# Expiry values are in seconds
# 1 day = 86400
# Add a new test in the following way
# eg
# ---
# ExampleTest: 86400
---
Example: 86400
ViewDrivingLicence: 259200
FinderAnswerABTest: 3628800 # 6 Weeks
BrexitLandingPageTest: 86400 # 1 day
