# Please leave the 'Example' test config in place and active.
#
# You should create <test name>_percentages.yaml to configure
# bucket allocations. See example_percentages.yaml for format.
---
Example: true
ElectricCarABTest: true
TransitionUrgency2: true
